# config/config.yaml

# Execution model
model: ollama               # or "openai"
model_name: hf.co/google/gemma-3-12b-it-qat-q4_0-gguf:latest    # used if Ollama is selected
generation_hour: 8          # for logging/reference

# Generation behavior
max_tweets: 5
topics: []                  # Empty now — test run mode

# Output channels
use_email: true
use_ui: false

email:
  from: "${SMTP_USER}"
  to: "ross.pingatore@gmail.com"
  subject: "Ross’s Daily Dispatch – Drafts Ready"
  smtp_server: "${SMTP_HOST}"
  smtp_port: ${SMTP_PORT}
  username: "${SMTP_USER}"
  password: "${SMTP_PASS}"